- name: 'Causes Office'
  aspect_ratio: 2.16
  zones:
    - { name: 'Ping Pong',        x: 0,    y: 0,    w: 0.09, h: 0.44 }
    - { name: 'Entrance',         x: 0.09, y: 0,    w: 0.17, h: 0.25 }
    - { name: 'Reception',        x: 0.26, y: 0,    w: 0.14, h: 0.19 }
    - { name: "Men's Room",       x: 0.4,  y: 0,    w: 0.11, h: 0.17 }
    - { name: "Women's Room",     x: 0.51, y: 0,    w: 0.11, h: 0.17 }
    - { name: 'Shower',           x: 0.62, y: 0,    w: 0.05, h: 0.17 }
    - { name: 'Mini Kitchen',     x: 0.67, y: 0,    w: 0.04, h: 0.17 }
    - { name: 'Janitor Closet',   x: 0.71, y: 0,    w: 0.05, h: 0.17 }
    - { name: 'Goodall',          x: 0.76, y: 0,    w: 0.05, h: 0.17 }
    - { name: 'Huerta',           x: 0.81, y: 0,    w: 0.05, h: 0.17 }
    - { name: 'Banks',            x: 0.86, y: 0,    w: 0.14, h: 0.17 }
    - { name: 'Cigar',            x: 0,    y: 0.44, w: 0.06, h: 0.18 }
    - { name: 'Bar',              x: 0,    y: 0.62, w: 0.06, h: 0.25 }
    - { name: 'Lounge',           x: 0,    y: 0.87, w: 0.26, h: 0.13 }
    - { name: 'Dining Area',      x: 0.06, y: 0.44, w: 0.2,  h: 0.43 }
    - { name: 'The Last Supper',  x: 0.26, y: 0.81, w: 0.24, h: 0.19 }
    - { name: 'Freight Elevator', x: 0.5,  y: 0.83, w: 0.06, h: 0.17 }
    - { name: 'Lobby',            x: 0.09, y: 0.25, w: 0.17, h: 0.19 }
    - { name: 'Mother Jones',     x: 0.28, y: 0.28, w: 0.07, h: 0.13 }
    - { name: 'Situation',        x: 0.28, y: 0.41, w: 0.09, h: 0.21 }
    - { name: 'Gandhi',           x: 0.28, y: 0.62, w: 0.07, h: 0.13 }
    - { name: 'Mandela',          x: 0.37, y: 0.26, w: 0.07, h: 0.13 }
    - { name: 'Snack',            x: 0.37, y: 0.39, w: 0.09, h: 0.25 }
    - { name: 'Parks',            x: 0.37, y: 0.64, w: 0.07, h: 0.13 }
    - { name: 'Cavell',           x: 0.48, y: 0.25, w: 0.07, h: 0.13 }
    - { name: 'Kitchen',          x: 0.47, y: 0.38, w: 0.09, h: 0.27 }
    - { name: 'Mother Teresa',    x: 0.48, y: 0.65, w: 0.07, h: 0.13 }
    - { name: 'Server',           x: 0.56, y: 0.25, w: 0.07, h: 0.13 }
    - { name: 'Dunant',           x: 0.64, y: 0.25, w: 0.07, h: 0.13 }
    - { name: 'MLK',              x: 0.56, y: 0.38, w: 0.15, h: 0.27 }
    - { name: 'Keller',           x: 0.56, y: 0.65, w: 0.07, h: 0.13 }
    - { name: 'Borlaug',          x: 0.92, y: 0.17, w: 0.08, h: 0.14 }
    - { name: 'Bono',             x: 0.92, y: 0.31, w: 0.08, h: 0.14 }
    - { name: 'Tubman',           x: 0.92, y: 0.45, w: 0.08, h: 0.14 }
    - { name: 'Skopistan',        x: 0.92, y: 0.59, w: 0.08, h: 0.41 }
    - { name: 'Work Area A',      x: 0.71, y: 0.17, w: 0.21, h: 0.64 }
    - { name: 'Work Area B',      x: 0.56, y: 0.81, w: 0.36, h: 0.19 }
- name: 'Outside'
  aspect_ratio: 4
  zones:
    - { name: 'Coffee Shop',      x: 0,    y: 0,    w: 0.25, h: 1 }
    - { name: 'Home',             x: 0.25, y: 0,    w: 0.25, h: 1 }
    - { name: 'Out to Lunch',     x: 0.5,  y: 0,    w: 0.25, h: 1 }
    - { name: 'Do not disturb',   x: 0.75, y: 0,    w: 0.25, h: 1 }
